imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.achievement_images: /images/achievements
    app.path.gallery_images: /images/galleries

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     sql.karas1993.nazwa.pl
        port:     3306
        dbname:   karas1993
        user:     karas1993
        password: Kkoaw1492
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

services:
    fos_user.doctrine_registry:
        alias: doctrine

easy_admin:
    site_name: 'Panel administratora'
    design:
            color_scheme: 'light'
            brand_color: '#73a839'
    entities:
      Advertisement:
        label: 'Ogłoszenia'
        class: AppBundle\Entity\Advertisement
        form:
          fields:
            - { property: 'title', label: 'tytuł ogłoszenia' }
            - { property: 'text', label: 'treść ogłoszenia', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
            - { property: 'author', label: 'autor ogłoszenia' }
            - { property: 'date', label: 'data ogłoszenia' }
        list:
          title: 'Ogłoszenia'
          fields:
           - { property: 'title', label: 'tytuł ogłoszenia' }
           - { property: 'text', label: 'treść ogłoszenia' }
           - { property: 'author', label: 'autor ogłoszenia' }
           - { property: 'date', label: 'data ogłoszenia' }
          actions:
                                   - { name: 'new', label: 'nowe ogłoszenie' }
                                   - { name: 'edit', label: 'modyfikuj ogłoszenie' }
                                   - { name: 'show', label: 'pokaż ogłoszenie' }
                                   - { name: 'search', label: 'wyszukaj' }
                                   - { name: 'delete', label: 'usuń' }

      Achievement:
              label: 'Osiągnięcia'
              class: AppBundle\Entity\Achievement
              form:
                fields:
                  - { property: 'imageFile', label:'obrazek', type: 'file' }
                  - { property: 'year', label:'rok szkolny'}
              list:
                title: 'osiągnięcia'
                fields:
                 - { property: 'image', type: 'image', label:'obrazek',base_path: %app.path.achievement_images% }
                 - { property: 'year', label:'rok szkolny'}
                actions:
                                         - { name: 'new', label: 'nowe osiągnięcie' }
                                         - { name: 'edit', label: 'modyfikuj osiągnięcie' }
                                         - { name: 'show', label: 'pokaż osiągnięcie' }
                                         - { name: 'search', label: 'wyszukaj' }
                                         - { name: 'delete', label: 'usuń' }
      Gallery:
                    label: 'Galerie'
                    class: AppBundle\Entity\Gallery
                    form:
                      fields:
                        - { property: 'imageFile', label:'obrazek', type: 'file' }
                        - { property: 'year', label:'rok szkolny'}
                        - { property: 'name', label:'nazwa galerii'}
                        - { property: 'href', label:'link do galerii'}
                    list:
                      title: 'Galerie'
                      fields:
                       - { property: 'image', type: 'image', label:'obrazek',base_path: %app.path.gallery_images% }
                       - { property: 'year', label:'rok szkolny'}
                       - { property: 'name', label:'nazwa galerii'}
                       - { property: 'href', label:'link do galerii'}
                      actions:
                                               - { name: 'new', label: 'nowa galeria' }
                                               - { name: 'edit', label: 'modyfikuj galerie' }
                                               - { name: 'show', label: 'pokaż galerie' }
                                               - { name: 'search', label: 'wyszukaj' }
                                               - { name: 'delete', label: 'usuń' }

      Year:
                    label: 'Rok szkolny'
                    class: AppBundle\Entity\Year
                    form:
                      fields:
                        - { property: 'schoolYear', label:'rok szkolny'}
                    list:
                      title: 'rok szkolny'
                      fields:
                       - { property: 'schoolYear', label:'rok szkolny'}
                      actions:
                                               - { name: 'new', label: 'nowy rok szkolny ' }
                                               - { name: 'edit', label: 'modyfikuj rok' }
                                               - { name: 'show', label: 'pokaż rok' }
                                               - { name: 'search', label: 'wyszukaj' }
                                               - { name: 'delete', label: 'usuń' }

      Article:
                    label: 'kącik logopedyczny'
                    class: AppBundle\Entity\Article
                    form:
                      fields:
                         - { property: 'title', label: 'tytuł artykułu' }
                         - { property: 'article', label: 'treść artykułu', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
                         - { property: 'author', label: 'autor ogłoszenia' }
                    list:
                      title: 'Publikacje'
                      fields:
                         - { property: 'title', label: 'tytuł artykułu' }
                         - { property: 'article', label: 'treść artykułu' }
                         - { property: 'author', label: 'autor artykułu' }
                      actions:
                                               - { name: 'new', label: 'nowa publikacja' }
                                               - { name: 'edit', label: 'modyfikuj publikacje' }
                                               - { name: 'show', label: 'pokaż publikacje' }
                                               - { name: 'search', label: 'wyszukaj' }
                                               - { name: 'delete', label: 'usuń' }


vich_uploader:
    db_driver: orm
    mappings:
        achievement_images:
            uri_prefix:         %app.path.achievement_images%
            upload_destination: %kernel.root_dir%/../web/images/achievements
        gallery_images:
                    uri_prefix:         %app.path.gallery_images%
                    upload_destination: %kernel.root_dir%/../web/images/galleries

ivory_ck_editor:
    default_config: "default"
    configs:
        default:
            toolbar:             "full"